### ISSUE TITLE
Basic NLP course coursera videos not there.

### ISSUE THREAD

**Issue by haskarb** [Shujian2015/FreeML#2]
Videos Deleted. Any other source?

**Comment by Shujian2015** [comment]
That's very sad. I didn't find any other source. Seems nowadays people just use deep learning models for NLP.

**Comment by Anirudh257** [comment]
Is this the course: [Stanford NLP](https://www.youtube.com/watch?v=OQQ-W_63UgQ&list=PL3FW7Lu3i5Jsnh1rnUwq_TcylNr7EkRe6)

**Comment by Shujian2015** [comment]
That's the NLP course with DL method. The one with the statistical methods is totally different. Now I can only find the first two lectures: https://www.youtube.com/playlist?list=PL8FFE3F391203C98C
